apiVersion: v1
kind: Service
metadata:
  name: "${{ values.repoName }}"
  labels:
    app: "${{ values.repoName }}"
spec:
  ports:
    - port: ${{ values.port }}
      targetPort: ${{ values.port }}
  selector:
    app: "${{ values.repoName }}"