apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backstage-automation-engine
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/IvayloB84/ArgoCD-RootApps.git"
        revision: main
        directories:
          - path: "argocd-apps/*"
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: "{{path.basename}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "{{path}}"
    spec:
      project: default
      source:
        repoURL: "https://github.com/IvayloB84/ArgoCD-RootApps.git"
        targetRevision: main
        path: "{{path}}/k8s"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
