apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backstage-automation-engine
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/IvayloB84/ArgoCD-RootApps"
        revision: main
        files:
          - path: "argocd-apps/*/config.yaml"
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: "{{appName}}" # Populated by config.json
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "argocd-apps/{{appName}}"
    spec:
      project: default
      source:
        repoURL: "{{repoURL}}"
        targetRevision: "{{targetRevision}}"
        path: "{{path}}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true