apiVersion: argoproj.io/v1alpha1
kind: AppSourceAllowList
metadata:
  name: "${{ values.repoName }}-allow-list"
  namespace: argocd
spec:
  allow:
    - group: "apps"
      kind: "Deployment"
    - group: ""
      kind: "Service"