apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.repoName | lower }}
  description: "${{ values.description }}"
  links:
    - url: /create/templates/default/deactivate-service-pipeline?template_args[repoName]=${{ values.repoName | lower }}
      title: Request Component Deactivation
      icon: help
  annotations:
    github.com/project-slug: "${{ values.repoOwner }}/${{ values.repoName }}"
    argocd/app-name: "${{ values.repoName }}"
    backstage.io/kubernetes-label-selector: "app=${{ values.repoName }}"
spec:
  type: service
  lifecycle: experimental
  owner: "user:default/${{ values.repoOwner }}"