apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.repoName }}
  labels:
    app: ${{ values.repoName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.repoName }}
  template:
    metadata:
      labels:
        app: ${{ values.repoName }}
    spec:
      containers:
        - name: app-container
          # Maps the image selection from the dropdown form dynamically
          image: ${{ values.serviceImage }}
          ports:
            # Maps the specific port selection from the dropdown form dynamically
            - containerPort: ${{ values.servicePort }}