apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.repoName }}
  namespace: default
  labels:
    backstage.io/kubernetes-id: ${{ values.repoName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      backstage.io/kubernetes-id: ${{ values.repoName }}
  template:
    metadata:
      labels:
        backstage.io/kubernetes-id: ${{ values.repoName }}
    spec:
      containers:
        - name: app
          image: ${{ values.image }}
          ports:
            - containerPort: ${{ values.port }}