apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: target-production-apps
resources:
  - ../../base
images:
  - name: ghcr.io/{{ values.owner }}/{{ values.name }}
    newTag: latest
replicas:
  - name: {{ values.name }}
    count: 1
