# syntax=docker/dockerfile:1
FROM maven:3.9-eclipse-temurin-${{ values.javaVersion }} AS build
WORKDIR /app
COPY pom.xml .
RUN mvn -B dependency:go-offline
COPY src src
RUN mvn -B package -DskipTests

FROM eclipse-temurin:${{ values.javaVersion }}-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE ${{ values.port }}
ENTRYPOINT ["java", "-jar", "/app/app.jar"]