apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: remote-centralized-templates
  description: Index of all pipeline scaffolding template cards
spec:
  type: url
  targets:
    - https://raw.githubusercontent.com/IvayloB84/backstage-templates/refs/heads/main/manifests/github-repo-template.yaml
    - https://raw.githubusercontent.com/IvayloB84/backstage-templates/refs/heads/main/manifests/create-guarded-component.yaml
    - https://raw.githubusercontent.com/IvayloB84/backstage-templates/refs/heads/main/manifests/deactivate-component-template.yaml