apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: remote-centralized-templates
  description: Index of all pipeline scaffolding template cards
spec:
  targets:
    - ./github-repo-template.yaml
    - ./create-guarded-component.yaml
    - ./deactivate-guarded-component.yaml