apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "${{ values.repoName }}"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: "argocd-apps/${{ values.repoName }}"
spec:
  project: default
  source:
    repoURL: "https://github.com/${{ values.repoOwner }}/ArgoCD-RootApps.git"
    targetRevision: main
    path: "argocd-apps/${{ values.repoName }}/k8s"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
