apiVersion: apps/v1
kind: Deployment
metadata:
  name: "${{ values.component_id }}"
  labels:
    app: "${{ values.component_id }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "${{ values.component_id }}"
  template:
    metadata:
      labels:
        app: "${{ values.component_id }}"
    spec:
      securityContext:
        fsGroup: 65534
      containers:
        # 1. Nginx Unprivileged Production Core Web Server Engine
        - name: app-container
          image: "nginxinc/nginx-unprivileged:alpine"
          ports:
            - containerPort: 8085
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
          volumeMounts:
            - name: code-stream-volume
              mountPath: "/usr/share/nginx/html"
            - name: config-volume
              mountPath: "/etc/nginx/conf.d/default.conf"
              subPath: "default.conf"
          resources:
            requests:
              cpu: "25m"
              memory: "16Mi"
            limits:
              cpu: "150m"
              memory: "32Mi"

        # 2. Automated Git-Sync Synchronization Engine
        - name: git-sync-sidecar
          image: "registry.k8s.io/git-sync/git-sync:v4.7.1"
          args:
            - "--repo=https://github.com/${{ values.destination.owner }}/${{ values.destination.repo }}.git"
            - "--branch=main"
            - "--depth=1"
            - "--wait=10"
            - "--root=/tmp/git"
            - "--dest=${{ values.destination.repo }}"
          volumeMounts:
            - name: code-stream-volume
              mountPath: /tmp/git
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534

      volumes:
        - name: code-stream-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            name: "${{ values.component_id }}-nginx-config"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "${{ values.component_id }}-nginx-config"
data:
  default.conf: |
    server {
        listen       8085;
        listen  [::]:8085;
        server_name  localhost;

        location / {
            root /usr/share/nginx/html/${{ values.destination.repo }};
            autoindex on;
            try_files \$uri \$uri/ @spa;
        }

        location @spa {
            root /usr/share/nginx/html/${{ values.destination.repo }};
            try_files /index.html =404;
        }
    }