apiVersion: v1
kind: Service
metadata:
  name: "${{ values.repoName }}-proxy-svc"
  labels:
    app: "${{ values.repoName }}-proxy"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: ${{ values.port }}
      protocol: TCP
      name: http
  selector:
    app: "${{ values.repoName }}-proxy"